export type {
  ActivityActor,
  ActivityDiagnostic,
  ActivityItem,
  ActivityRequest,
  ActivityResponse,
  ActivitySource,
  ActivitySubject,
  BootstrapResponse,
  CapabilityStatus,
  CodeKnowledgeHit,
  CodeKnowledgeRequest,
  CodeKnowledgeResponse,
  CodeWorkspaceRequest,
  CodeWorkspaceResponse,
  CodeWorkspaceView,
  GraphHealthDetails,
  GraphIndexStatus,
  GraphRelation,
  GraphSourcePage,
  GraphSourceProjection,
  GraphSymbol,
  GraphSymbolId,
  HealthResponse,
  HomeResponse,
  HubActor,
  HubCapabilities as CapabilitiesResponse,
  HubJobKind as JobKind,
  HubJobProgress as JobProgress,
  HubJobSnapshot as JobSummary,
  HubJobState as JobState,
  HubProblemDetails as ProblemDetails,
  JobPageResponse as JobsResponse,
  JobStartRequest as StartJobRequest,
  SearchRequest,
  SearchResult,
  SearchResponse,
  SourceSearchResult,
  SpecDetailProjection,
  SpecDetailResponse,
  SpecEntityKind,
  SpecHierarchyRelation,
  SpecIndexProjection,
  SpecListPageProjection,
  SpecListRequest,
  SpecListResponse,
  SpecSummaryProjection,
  SymbolSearchResult,
  SessionResponse,
  TeamActivityEvent,
  TeamActivitySubjectInput,
  TeamActorRef,
  TeamCurrentActorResponse,
  TeamGitAlias,
  TeamMember,
  TeamMemberListRequest,
  TeamMemberListResponse,
  TeamOperationApplyRequest,
  TeamOperationApplyResponse,
  TeamOperationPreviewRequest,
  TeamOperationPreviewResponse,
  TeamWorkstream,
  TeamWorkstreamListRequest,
  TeamWorkstreamListResponse,
  TeamWorkstreamState,
  WikiSearchResult,
  WikiBacklinksRequest,
  WikiBacklinksResponse,
  WikiEntityDetailResponse,
  WikiEntityId,
  WikiEntityListRequest,
  WikiEntityListResponse,
  WikiEntitySummary,
  WikiGrounding,
  WikiGroundingHealth,
  WikiHealthDetails,
  WikiIndexStatus,
  WikiLifecycleState,
  WikiProvenance,
  WikiRelation,
  WikiRelationHit,
  WikiRelationsRequest,
  WikiRelationsResponse,
  WikiSource,
} from "@mex/hub-contracts";

export type CapabilityName = "graph" | "wiki" | "jobs" | "activity" | "members" | "workstreams" | "specs" | "team";
export type Tone = "neutral" | "info" | "success" | "warning" | "danger";
